<div class="mt-5 w-25 mx-auto ">
  <p class="alert alert-info">editar categoria</p>
  <form action="./editarcategoria/<?= $id ?>" method="POST">
    <div class="form-group" class="mt-5 w-25 mx-auto ">
      <label for="">genero</label>
      <input type="text" name="genero" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mx-auto d-block mt-5 w-25 mx-auto ">enviar</button>



  </form>

  <a type="submit" href="listar" class="btn btn-danger mt-5 w-20 mx-auto ">volver</a>
</div>