<?php
include_once 'templates/header.phtml'; ?>
<div class="mt-5 w-25 mx-auto ">
  <form method="POST" action="verify">
    <div class="form-group  ">
      <label for="exampleInputEmail1 ">Usuario</label>
      <input type="text" class="form-control form-control-sm " id="exampleInputEmail1" aria-describedby="emailHelp"
        placeholder="Ingrese el usuario " type="text" id="email" name="email">

    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control form-control-sm " id="exampleInputPassword1" placeholder="Password"
        type="password" name="password" id="password">
    </div>
    <?php if ($error): ?>
      <div class='alert alert-danger' role='alert'>
        <?= $error ?>
      </div>
    <?php endif ?>
    <button type="submit" class="btn btn-primary mx-auto d-block">enviar</button>
  </form>
</div>

<?php
