<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Musica</title>
  <base href="<?= BASE_URL ?>">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>



  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Musica</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="listar">administracion</a>
          </li>
          <li class="nav-item">
            <?php if (!isset($_SESSION['ID_USUARIO'])): ?>
            <li class="nav-item">
              <a class="nav-link active" href="login" style="color: green;">iniciar session</a>
            </li>
          <?php else: ?>
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link active" href="logout" style="color: red;">cerrar session</a>
            </div>

          <?php endif ?>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="home">albumes</a>

          </li>
        </ul>
      </div>
    </div>
  </nav>

</body>

</html>